# Generated by Django 6.0.1 on 2026-01-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
                ('personal_email', models.CharField(max_length=255)),
                ('locker_number', models.IntegerField(unique=True)),
                ('locker_combination', models.CharField(default='12-12-12')),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
